default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tp1_restaurant_ranker_development

test:
  <<: *default
  database: tp1_restaurant_ranker_test

production:
  <<: *default
  database: tp1_restaurant_ranker_production
  password: <%= ENV["RESTAURANT_RANKER_DATABASE_PASSWORD"] %>